name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 12
      - run: npm i
      - run: npm test
      - run: npm run build
