name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 12
        run: echo 'Testing bash'
      - run: npm i
      - run: npm test
      - run: npm run build
